src/linux/syscall-linux.c: fix build failure on -std=c23
Without the change the build fails due to type mismatch as:

    linux/syscall-linux.c: In function 'doSyscall':
    linux/syscall-linux.c:3807:24: error: assignment to '__sighandler_t' {aka 'void (*)(int)'} from incompatible pointer type 'void (*)(void)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Win
    tible-pointer-types-Wincompatible-pointer-types8;;]
     3807 |         act.sa_handler = (void (*)()) (long) sa->lia_handler;
          |                        ^

C23 turned `void (*)()` into `void (*)(void)` insteaof partially defined
type. Pet's explicitly specify the handler type as used by
`sigaction()`.