src/linux/syscall-linux.c: call 'uselib' syscall directly
On modern linux build fails as:

```
ld: ./.libs/libski.a(syscall-linux.o): in function `doSyscall':
src/linux/syscall-linux.c:2676: undefined reference to `uselib'
```

Issue syscall directly instead of trying to call
removed glibc wrapper.

Fixed by Mike Frysinger <vapier@gentoo.org> at
https://bugs.gentoo.org/592226

Bug: https://bugs.gentoo.org/592226
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>