src/linux/dwarf-linux.c: use 'void *' directly instead of PTR (binutils-2.39)
binutils-2.39 removed 'PTR' compatibility define in favour of 'void *'.
This exposed the following build failure:

    linux/dwarf-linux.c:100:46: error: unknown type name 'PTR'; did you mean 'CTR'?
      100 | find_in_section (bfd * bfd, asection * sect, PTR obj)
          |                                              ^~~
          |                                              CTR