src/ssDSym.c: fix build failure on -std=c23
Without the change the build fails due to type mismatch as:

    ./escan.l: In function 'getVal':
    ./escan.l:156:20: error: too many arguments to function 'psym->getFn'
      156 |             return psym->getFn(viewPid);
          |                    ^~~~

C23 turned `REG (*)()` into `REG (*)(void)` instead of partially defined
type. `src/ssDSym.c` exploited partial definedness to store different
function accessor types. The change splits accessors into different
fields.