src/dos.c: drop unused <ustat.h> inclusion
On glibc-2.28 build fails as:

```
dos.c:53:10: fatal error: ustat.h: No such file or directory
 #include <ustat.h>
          ^~~~~~~~~
```

dos.c does not seem to use ustat struct or stat() syscall.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>