src/linux/syscall-linux.c: drom <asm/page.h> inclusion
Fix build failure due to use of outdated include:

```
linux/syscall-linux.c:75:10: fatal error: asm/page.h: No such file or directory
 #include <asm/page.h>
          ^~~~~~~~~~~~
```

Patch by Dennis Schridde at https://bugs.gentoo.org/376411

Bug: https://bugs.gentoo.org/376411
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>